language: java
jdk:
  - oraclejdk8
install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

after_success:
  - mvn jacoco:report coveralls:report -DrepoToken=$COVERALLS_REPO_TOKEN
